### ISSUE TITLE
Idea: command for inverse of dfm add

### ISSUE THREAD

**Issue by marconett** [CGamesPlay/dfm#1]
Hi,

I just started using this and i like it. I think of it as kind of a convenient wrapper for `ln` ;)
With this in mind, what would you think about a "unlink" command that does the opposite of what "link" does?

**Comment by CGamesPlay** [comment]
There's `dfm remove` (try `dfm help remove`) to remove all linked files. Were you looking for a command that would unlink a specific one?

Can you add a bit more information about your use case and goals so we can find the simplest possible solution?

**Comment by marconett** [comment]
say I do `dfm add .vimrc`. that creates a symling `.vimrc -> ~/dotfiles/file.vimrc`.
later on, i decide i don't want to keep my vimrc in my dfm repo.

now to remove it from the dfm repo, i need to manually remove the symlink and move the file back `rm .vimrc && mv ~/dotfiles/file.vimrc .`

might be a bit nitpicky..

**Comment by marconett** [comment]
sorry, just noticed i talked about `link` in my original post, where i actually mean `add`. so being consistent with the current command names, i suppose the best name for my proposed command would be "remove".

**Comment by CGamesPlay** [comment]
The idea of dfm removing files from the repository isn't very clean in the preferred use case: when you run this command on `machine-a`, it will do what you want. When you push those changes to git and run `dfm link` on `machine-b`, it will actually remove the file entirely from that machine. So it's a bit confusing.

I do think this is a valid use case. Let me think about some options. Right now I'm thinking a viable thing would be a `dfm copy` for a specific file, and adding a `--no-track` flag to the command so it doesn't get added to the cleanup manifest.

**Comment by CGamesPlay** [comment]
OK, I am not going to add a command to remove the file from the repository to dfm. Instead, I'm going to make some changes that make this use case less awkward to deal with. Namely:
1. `link`, `copy`, and `remove` will all take file arguments so that they can be run on specific paths.
2. `export` will be added.

Here's my rationale: `dfm add` is actually a convenience provided by dfm that replaces the following shell script:

```bash
function dfm_add() {
    mv ~/$1 $DFM_DIR/files/$1
    dfm link $1
}
```

Well, almost. Actually `dfm link` doesn't accept a specific file to link, so that's change 1. What's the inverse of this script? Well if `dfm link` is an analogy to `ln`, then the inverse is this shell script:

```bash
function dfm_export() {
    dfm remove $1
    mv $DFM_DIR/files/$1 ~/$1
}
```

Now, I'm not comfortable with this script, because the `mv` results in weird semantics when you share your dfm repository between multiple machines (it's helpful to imagine using Dropbox as the shared folder, rather than git). However, I'm fine with using `cp` instead of `mv`.

I tossed around a few names for this, but I think `export` is the most natural. Note that `dfm add` is already aliased as `dfm import`, so you can use import/export to think of them as natural inverses.

I'll take a stab at implementing these changes. Thanks for the feedback!

**Comment by CGamesPlay** [comment]
I ended up going with "eject" instead of "export", but this is done now, and available in https://github.com/CGamesPlay/dfm/releases/tag/v1.1.0

Thanks for the feedback! Let me know if there's anything else that you notice missing/wrong with dfm!
